# Generated by Django 3.0.7 on 2020-06-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='large_price',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='pizza',
            name='medium_price',
            field=models.FloatField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='pizza',
            name='small_price',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
