# Generated by Django 3.0.7 on 2020-06-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200630_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pizzas',
            new_name='pizza',
        ),
    ]
